### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by eddieantonio** [eddieantonio/imgcat#1]
- [x] Python script to generate kd-tree
 - [x] Get 256 color mapping
 - [x] Determine terminal color depth
 - [x] Write printing function
 - [x] Write rescale
 - [x] Check if is a tty.
 - [x] Argument parsing
   - [x] Option: `--depth` (force colour depth)
   - [x] Option `--no-resize`
   - [x] Option: `--width`
 - [x] Remove need for aggressive assertions
 - [x] Install
 - [x] Manpage
 - [x] Package for package managers
 - [x] Get ~~8~~ ~~16~~ 8 color mapping
 - [x] ~~More compatible [static assert](http://stackoverflow.com/a/3385694)~~
 - [x] Make pixel test.
 - [x] Automatic testing (47454d7c93)
 - [x] ~~Cross-platform continuous integration~~
 - [x] Build sticker in README, because that is of utmost importance
 - [x] More illustrative front-page picture
 - [x] `--help` and `--version` options
 - [x] ~~Make some _real_ test cases~~
